### ISSUE TITLE
'[]' brackets in file path causes exception

### ISSUE THREAD

**Issue by kh000** [Kode/Kha#1102]
OS: Windows 10
kha used with Armory3d

Is it expected to throw an exception in shader parser while file path contains '[]'? Seems like it's being treated as a pattern from `node_modules\braces\lib\braces.js`
I have following file path `F:\gameDev\[2K]Concrete07\Concrete07_col.jpg`
and it throws:
```
F:\gameDev\armory\ArmorySDK\Kha\Tools\khamake\node_modules\snapdragon\lib\parser.js:473
        throw new Error('no parsers registered for: "' + self.input.slice(0, 5) + '"');
        ^

Error: no parsers registered for: "]Conc"
    at parse (F:\gameDev\armory\ArmorySDK\Kha\Tools\khamake\node_modules\snapdragon\lib\parser.js:473:15)
    at Parser.parse (F:\gameDev\armory\ArmorySDK\Kha\Tools\khamake\node_modules\snapdragon\lib\parser.js:477:24)
    at Snapdragon.parse (F:\gameDev\armory\ArmorySDK\Kha\Tools\khamake\node_modules\snapdragon\index.js:122:28)
    at Snapdragon.<anonymous> (F:\gameDev\armory\ArmorySDK\Kha\Tools\khamake\node_modules\braces\lib\braces.js:40:45)
    at Braces.parse (F:\gameDev\armory\ArmorySDK\Kha\Tools\khamake\node_modules\braces\lib\braces.js:66:26)
    at Braces.expand (F:\gameDev\armory\ArmorySDK\Kha\Tools\khamake\node_modules\braces\lib\braces.js:87:18)
    at create (F:\gameDev\armory\ArmorySDK\Kha\Tools\khamake\node_modules\braces\index.js:142:15)
    at memoize (F:\gameDev\armory\ArmorySDK\Kha\Tools\khamake\node_modules\braces\index.js:298:13)
    at Function.braces.create (F:\gameDev\armory\ArmorySDK\Kha\Tools\khamake\node_modules\braces\index.js:165:10)
    at Function.braces.expand (F:\gameDev\armory\ArmorySDK\Kha\Tools\khamake\node_modules\braces\index.js:81:17)
```

after rename from the following file path `F:\gameDev\[2K]Concrete07\Concrete07_col.jpg`
to `F:\gameDev\Concrete07\Concrete07_col.jpg` (removed **[2K]**) it parsed correctly.

**Comment by RobDangerous** [comment]
Please register a parser for Conc.

**Comment by kh000** [comment]
I don't think its the case. When I add another lets say 2 textures in paths:
```
F:\gameDev\[4K]Plastic\Plastic_col.jpg
F:\gameDev\[2K]Grass\Grass02_col.jpg
```
I will get another 2 exceptions:
```
Error: no parsers registered for: "]Plas"
Error: no parsers registered for: "]Gras"
```
So for each directory in file path i need to register parser?
I strongly believe that brackets `[]` cannot be used in file path, because they are interpreted as pattern or something.

**Comment by RobDangerous** [comment]
Hey, it was a joke. Of course it should not freak out about some brackets. Also I don't think there's any way to register a Conc.
