### ISSUE TITLE
error when processing jpg assets

### ISSUE THREAD

**Issue by romamik** [Kode/Kha#1234]
Steps to reproduce:
* init empty project with `make --init`
* copy any jpg file to `Assets` folder
* try to build project with `make html5`
Error
```
(node:9676) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "file" argument must be of type string. Received undefined
    at validateString (internal/validators.js:121:11)
    at normalizeSpawnArguments (child_process.js:406:3)
    at Object.spawn (child_process.js:546:13)
    at c:\work\taonga-mobile\banan\Kha\Tools\khamake\out\ImageTool.js:16:37
    at new Promise (<anonymous>)
    at getWidthAndHeight (c:\work\taonga-mobile\banan\Kha\Tools\khamake\out\ImageTool.js:8:12)
    at Object.exportImage (c:\work\taonga-mobile\banan\Kha\Tools\khamake\out\ImageTool.js:137:24)
    at Html5Exporter.copyImage (c:\work\taonga-mobile\banan\Kha\Tools\khamake\out\Exporters\Html5Exporter.js:206:40)
    at convertAsset (c:\work\taonga-mobile\banan\Kha\Tools\khamake\out\AssetConverter.js:149:62)
    at FSWatcher.<anonymous> (c:\work\taonga-mobile\banan\Kha\Tools\khamake\out\AssetConverter.js:237:31)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:9676) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:9676) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
This is because `options` object does not have `kraffity` field. Tested with latest kha.

**Comment by romamik** [comment]
Looks like the problem was added with khamake commit 694d5dbba8137d866c10d70a4680475afda9841b "add --kraffiti cmdline option".
