### ISSUE TITLE
Mixing g1 and g2 doesn't work

### ISSUE THREAD

**Issue by dstrekelj** [Kode/Kha#452]
**What did I want to do?**

I wanted to use the `graphics1` API in conjunction with `graphics2` to perform some debug drawing.

**What did I do?**

Basically, this:

```haxe
import kha.Framebuffer;
import kha.Scheduler;
import kha.System;

class Main {
	public static function main() {
		System.init({title: "New Project"}, function () {
			System.notifyOnRender(render);
			Scheduler.addTimeTask(update, 0, 1 / 60);
		});
	}

	static function update(): Void {}

	static function render(frame: Framebuffer) {
		frame.g2.begin();
		frame.g2.fillRect(10, 10, 50, 50);
		frame.g1.setPixel(100, 100, kha.Color.Green);
		frame.g2.end();
	}
}
```

**What did I expect to happen?**

In the above example, I would expect a white rectangle and a green pixel to be drawn to the framebuffer and displayed on the screen.

**What actually did happen?**

Using KodeStudio 16.11.1 and its built-in version of Kha, the HTML5 debugger stopped at the following line:

```haxe
// File: kha/graphics2/Graphics1.hx

package kha.graphics2;

import haxe.io.Bytes;
import kha.Canvas;
import kha.Color;
import kha.graphics4.TextureFormat;
import kha.graphics4.Usage;
import kha.Image;

class Graphics1 implements kha.graphics1.Graphics {
	private var canvas: Canvas;
	private var texture: Image;
	private var pixels: Bytes;
	
	public function new(canvas: Canvas) {
		this.canvas = canvas;
	}
	
	public function begin(): Void {
		if (texture == null) {
			texture = Image.create(canvas.width, canvas.height, TextureFormat.RGBA32, Usage.ReadableUsage);
		}
		pixels = texture.lock();
	}
	
	public function end(): Void {
		texture.unlock();
		canvas.g2.begin();
		canvas.g2.drawImage(texture, 0, 0);
		canvas.g2.end();
	}
	
	public function setPixel(x: Int, y: Int, color: Color): Void {
--->		pixels.setInt32(y * texture.realWidth * 4 + x * 4, color);
	}
}
```

The debug console printed the following error and call stack (which, admittedly, isn't that useful as it points to lines in the debug build of the project):

```
TypeError: Cannot read property 'setInt32' of undefined
    at Object.setPixel (file:///F:/Projects/Haxe%20Projects/kha/jolt-sandbox/build/debug-html5/kha.js:13209:14)
    at Object.point (file:///F:/Projects/Haxe%20Projects/kha/jolt-sandbox/build/debug-html5/kha.js:199:30)
    at Function.jolt_Painter.paintCircle (file:///F:/Projects/Haxe%20Projects/kha/jolt-sandbox/build/debug-html5/kha.js:1230:5)
    at Object.render (file:///F:/Projects/Haxe%20Projects/kha/jolt-sandbox/build/debug-html5/kha.js:238:16)
    at f (file:///F:/Projects/Haxe%20Projects/kha/jolt-sandbox/build/debug-html5/kha.js:19320:242)
    at Function.kha_System.render (file:///F:/Projects/Haxe%20Projects/kha/jolt-sandbox/build/debug-html5/kha.js:3326:3)
    at animate (file:///F:/Projects/Haxe%20Projects/kha/jolt-sandbox/build/debug-html5/kha.js:3691:15)
```

The Krom debugger did not give any result, as it did not respond and crashed.

**How can I reproduce?**

Latest KodeStudio at the time of writing (version 16.11.1) on Windows 10 64-bit. Run the code above using KodeStudio's HTML5 debugger.

**Comment by RobDangerous** [comment]
Oh, I just figured your code is wrong. Try...

```
frame.g2.begin();
frame.g2.fillRect(10, 10, 50, 50);
frame.g2.end();
frame.g1.begin();
frame.g1.setPixel(100, 100, kha.Color.Green);
frame.g1.end();
```

**Comment by Gavolot** [comment]
![image](https://user-images.githubusercontent.com/3579229/119310385-55696500-bc78-11eb-9d19-2925b294e6f8.png)
I understand that now is 2020. It looks pretty damn weird, but this is how it works.
