### ISSUE TITLE
AndroidExporter.exportAndroidStudioProject error

### ISSUE THREAD

**Issue by montonero** [Kode/Kha#613]
I get the following error trying to build Empty project:
```
➜  Empty git:(master) ✗ node Kha/make android
Creating Kha project.
Compiling shader 1 of 8 (painter-colored.frag.glsl).
Compiling shader 2 of 8 (painter-colored.vert.glsl).
Compiling shader 3 of 8 (painter-image.vert.glsl).
Compiling shader 4 of 8 (painter-image.frag.glsl).
Compiling shader 5 of 8 (painter-text.frag.glsl).
Compiling shader 6 of 8 (painter-text.vert.glsl).
Compiling shader 7 of 8 (painter-video.frag.glsl).
Compiling shader 8 of 8 (painter-video.vert.glsl).
TypeError: name.replaceAll is not a function

    at AndroidExporter.exportAndroidStudioProject (/Users/haxe_user/haxe/Empty/Kha/Tools/khamake/out/Exporters/AndroidExporter.js:65:29)
    at AndroidExporter.<anonymous> (/Users/haxe_user/haxe/Empty/Kha/Tools/khamake/out/Exporters/AndroidExporter.js:60:18)
    at Generator.next (<anonymous>)
    at /Users/haxe_user/haxe/Empty/Kha/Tools/khamake/out/Exporters/AndroidExporter.js:7:65
    at __awaiter (/Users/haxe_user/haxe/Empty/Kha/Tools/khamake/out/Exporters/AndroidExporter.js:3:12)
    at AndroidExporter.exportSolution (/Users/haxe_user/haxe/Empty/Kha/Tools/khamake/out/Exporters/AndroidExporter.js:57:16)
    at /Users/haxe_user/haxe/Empty/Kha/Tools/khamake/out/main.js:206:46
    at Generator.next (<anonymous>)
    at /Users/haxe_user/haxe/Empty/Kha/Tools/khamake/out/main.js:7:65
    at __awaiter (/Users/haxe_user/haxe/Empty/Kha/Tools/khamake/out/main.js:3:12)
```

**Comment by RobDangerous** [comment]
Did you update the Kha submodule or did you use the older version Empty points to?

**Comment by montonero** [comment]
oh, my bad. updating submodules fixed this.
