### ISSUE TITLE
Cannot compile under macOS

### ISSUE THREAD

**Issue by gmisail64** [Kode/Kha#728]
My Kha application was not compiling under macOS, so I decided to update my Kha version. Now, none of the platforms will compile because of a khamake build error:

```
async function runKhamake() {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/gmisail/Desktop/Torch/Kha/Tools/khamake/khamake.js:1:63)
    at Module._compile (module.js:541:32)
```
I updated to the newest git version of Kha.

**Comment by RobDangerous** [comment]
That looks like you need to update your node.js version but khamake should print a proper error message about that so that‘s a bit strange. What is your node.js-version?

**Comment by gmisail64** [comment]
My node version v6.2.2, i could've sworn i updated it. it is odd that it compiled fine under the previous kha version, it must've been backwards-compatible up until that update i guess

**Comment by gmisail64** [comment]
yes, that solved it.
