### ISSUE TITLE
TypeError: project.addExcludes is not a function

### ISSUE THREAD

**Issue by r3d9u11** [Kode/Kha#754]
Hi. I'm trying to add instruction:
```
project.addExcludes('Backends/Kore/khacpp/src/hx/Debugger.cpp');
project.addExcludes('Backends/Kore/khacpp/src/hx/Profiler.cpp')
project.addExcludes('Backends/Kore/khacpp/src/hx/Telemetry.cpp');
```
to khafile.js, but unfortunally making process was excepted:
```
$ node Kha/make --target linux --compile
Creating Kha project.
TypeError: project.addExcludes is not a function
    at eval (eval at fs.readFile (/home/r3d9u11/Desktop/Empty/Kha/Tools/khamake/out/ProjectFile.js:48:21), <anonymous>:22:9)
    at fs.readFile (/home/r3d9u11/Desktop/Empty/Kha/Tools/khamake/out/ProjectFile.js:48:119)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
Error: khafile.js did not call resolve, no project created.
```
what I'm doing wrong?
I'm trying to compile project with debugging information.
[Empty-Debug.zip](https://github.com/Kode/Kha/files/1739208/Empty-Debug.zip)

**Comment by RobDangerous** [comment]
That's a korefile function, but see https://github.com/Kode/Kha/issues/628 for how to add the debugging files.
