### ISSUE TITLE
node11 not working with repo Kha on mac.

### ISSUE THREAD

**Issue by nanjizal** [Kode/Kha#900]
```
/projects/NanjizalNew/TrilateralRelated/TrilateralBazaar/jigsawX$ node Kha/make html5 --haxe3
Using Kha from /projects/NanjizalNew/TrilateralRelated/TrilateralBazaar/jigsawX/Kha
Creating Kha project.
Exporting asset 1 of 1 (tablecloth.jpg).
Compiling shader 1 of 8 (painter-colored.frag.glsl).
Compiling shader 2 of 8 (painter-colored.vert.glsl).
Compiling shader 3 of 8 (painter-image.frag.glsl).
Compiling shader 4 of 8 (painter-image.vert.glsl).
Compiling shader 5 of 8 (painter-text.frag.glsl).
Compiling shader 6 of 8 (painter-text.vert.glsl).
Compiling shader 7 of 8 (painter-video.frag.glsl).
Compiling shader 8 of 8 (painter-video.vert.glsl).
Done.
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn /projects/NanjizalNew/TrilateralRelated/TrilateralBazaar/jigsawX/Kha/Tools/haxe/v3.x/haxe-osx EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
    at onErrorNT (internal/child_process.js:407:16)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
```

**Comment by RobDangerous** [comment]
Aha, the executable bit isn't set for Haxe 3 on Mac. This nonetheless works with earlier Node versions?
