### ISSUE TITLE
kha application does not start on android

### ISSUE THREAD

**Issue by limbo127** [Kode/Kha#979]
Hello, 
start kha application with kode studio en html5 without issue.
Trying to build android app, no error in android studio, but when i'l trying to start kha application : 
$ adb install-multiple -r -t C:\Users\nicolas\Documents\console\build\android\New-Project\app\build\intermediates\resources\instant-run\debug\resources-debug.apk C:\Users\nicolas\Documents\console\build\android\New-Project\app\build\intermediates\split-apk\debug\slices\slice_0.apk C:\Users\nicolas\Documents\console\build\android\New-Project\app\build\intermediates\split-apk\debug\slices\slice_2.apk C:\Users\nicolas\Documents\console\build\android\New-Project\app\build\intermediates\split-apk\debug\slices\slice_1.apk C:\Users\nicolas\Documents\console\build\android\New-Project\app\build\intermediates\split-apk\debug\slices\slice_3.apk C:\Users\nicolas\Documents\console\build\android\New-Project\app\build\intermediates\split-apk\debug\slices\slice_4.apk C:\Users\nicolas\Documents\console\build\android\New-Project\app\build\intermediates\split-apk\debug\slices\slice_5.apk C:\Users\nicolas\Documents\console\build\android\New-Project\app\build\intermediates\split-apk\debug\slices\slice_6.apk C:\Users\nicolas\Documents\console\build\android\New-Project\app\build\intermediates\split-apk\debug\slices\slice_7.apk C:\Users\nicolas\Documents\console\build\android\New-Project\app\build\intermediates\split-apk\debug\slices\slice_8.apk C:\Users\nicolas\Documents\console\build\android\New-Project\app\build\intermediates\split-apk\debug\slices\slice_9.apk C:\Users\nicolas\Documents\console\build\android\New-Project\app\build\intermediates\instant-run-apk\debug\app-debug.apk 
Split APKs installed in 2 s 384 ms
$ adb shell am start -n "tech.kode.kha/tech.kode.kha.KhaActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Client not ready yet..Waiting for process to come online
Connected to process 7703 on device Nexus_5X_API_28 [emulator-5554]
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
I/tech.kode.kha: Not late-enabling -Xcheck:jni (already on)
W/tech.kode.kha: Unexpected CPU variant for X86 using defaults: x86
W/tech.kode.kha: JIT profile information will not be recorded: profile file does not exits.
I/chatty: uid=10085(tech.kode.kha) identical 9 lines
W/tech.kode.kha: JIT profile information will not be recorded: profile file does not exits.
I/InstantRun: starting instant run server: is main process
D/OpenGLRenderer: Skia GL Pipeline
D/: HostConnection::get() New Host Connection established 0xeb752580, tid 7755
I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
I/OpenGLRenderer: Initialized EGL, version 1.4
D/OpenGLRenderer: Swap behavior 1
W/OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
D/OpenGLRenderer: Swap behavior 0
D/EGL_emulation: eglCreateContext: 0xe2dea7a0: maj 3 min 0 rcv 3
D/EGL_emulation: eglMakeCurrent: 0xe2dea7a0: ver 3 0 (tinfo 0xe400edb0)
D/: HostConnection::get() New Host Connection established 0xe5a1d800, tid 7753
D/EGL_emulation: eglCreateContext: 0xe5a05120: maj 3 min 0 rcv 3
D/EGL_emulation: eglMakeCurrent: 0xe2dea7a0: ver 3 0 (tinfo 0xe400edb0)
D/EGL_emulation: eglMakeCurrent: 0xe5a05120: ver 3 0 (tinfo 0xe5a03670)
E/AndroidRuntime: FATAL EXCEPTION: GLThread 430
    Process: tech.kode.kha, PID: 7703
    java.lang.IllegalArgumentException: Unsupported flags: 256
        at java.util.regex.Pattern.<init>(Pattern.java:1324)
        at java.util.regex.Pattern.compile(Pattern.java:975)
        at haxe.root.EReg.__hx_ctor__EReg(EReg.java:86)
        at haxe.root.EReg.<init>(EReg.java:17)
        at sys.Http.customRequest(Http.java:83)
        at sys.Http.request(Http.java:67)
        at haxe.root.Main.getClientFromAwsApi(Main.java:434)
        at haxe.root.Main.main(Main.java:417)
        at kha.SystemImpl.preinit(SystemImpl.java:287)
        at tech.kode.kha.KhaRenderer.onSurfaceCreated(KhaRenderer.java:49)
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1539)
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1270)
D/EGL_emulation: eglMakeCurrent: 0xe2dea7a0: ver 3 0 (tinfo 0xe400edb0)
Application terminated.

Do you have any idea ?

**Comment by RobDangerous** [comment]
Well, it crashs in getClientFromAwsApi, whatever that is, while trying to do some http things.

**Comment by RobDangerous** [comment]
I can still see an http request in your stack trace.

**Comment by limbo127** [comment]
ok, without http request , there's no error but not display. Some other issue in my code perhaps, but
haxe.http api is not android compatible ?
nicolas

**Comment by RobDangerous** [comment]
The http API is a Haxe thing which I never touched, you'll need to raise the issue there. Sorry.
About the black screen, I can reproduce that via the Blocks sample even though the Texture sample works fine. Haven't found the cause yet. Meanwhile give the android-native target a try, that should also fix your http woes.

**Comment by limbo127** [comment]
I'm using Kode Studio 18.11
<https://github.com/Kode/KodeStudio/releases/tag/v18.11>
and a git version of kha from last week, but I can see some new commit from
the last two days, must i do sync ?
Nicolas


Le dim. 3 févr. 2019 à 20:26, Robert Konrad <notifications@github.com> a
écrit :

**Comment by RobDangerous** [comment]
Yes, that's what I was saying.

**Comment by limbo127** [comment]
Hello,
same error from android studio
1 - haxelib update
2 - build android native from kode studio
3 - start android studio and import gradle project
4 => android studio = External Native Build issues : Error Configuring :
SIMPLE : Error configuring
5=> if i'm trying to rebuild project from build android studio menu, a lot
of error as yesterday

Thanks
Nicolas

Le dim. 3 févr. 2019 à 21:55, Robert Konrad <notifications@github.com> a
écrit :

**Comment by limbo127** [comment]
Strange, Haxelib git kha <github kha> seems to ne good here.
I’m trying to delete.

Le lun. 4 févr. 2019 à 10:29, Robert Konrad <notifications@github.com> a
écrit :

**Comment by limbo127** [comment]
ok, you're right. haxelib git kha https://gitbub.com/Kode/kha  does not
install from the git repository specify in argument but from an old one !
it's very disapointing mostly when we are watching tutorial.
Thanks you for your help, android native build seems to be compile now.
Regards,
Nicolas

**Comment by RobDangerous** [comment]
I suppose you refer to some old video from Lubos. That was wrong even back when it was released. He posted an updated video a while ago though. And I don't know much about haxelib but I don't think it downloads old stuff, might have trouble with submodules maybe but more likely what really helped was deleting the build dir.

**Comment by luboslenco** [comment]
> I suppose you refer to some old video from Lubos.

Lubos has no knowledge of these events. 😃

**Comment by RobDangerous** [comment]
Aaah. The other guy who's name starts with an L. Sorry, it's Monday evening and I'm debugging self-compiled JavaScript.
